inherit:
- models/standard.yaml
- wandb.yaml
model:
  n_dims: 8
  n_positions: 101
test_run: false
training:
  batch_size: 256
  curriculum:
    dims:
      end: 8
      inc: 0
      interval: 2000
      start: 8
  data: modular_arithmetic
  keep_every_steps: 100000
  learning_rate: 0.001
  num_tasks: 256
  save_every_steps: 250000
  task_kwargs: {}
  train_steps: 1000001
